// scripts/topics.js
// 901 unique mystery topics across 6 categories
// Used by generate.js (daily) and bulk.js (bulk generation)

export const TOPICS = [
  { category: 'Cryptids', topics: [
    'Bigfoot','Loch Ness Monster','Chupacabra','Mothman','Jersey Devil',
    'Thunderbird','Dogman','Black Eyed Children','The Dover Demon','Yeti',
    'Skunk Ape','The Flatwoods Monster','Lizard Man of Scape Ore Swamp',
    'Ogopogo','The Loveland Frogman','The Altamaha-ha',
    'The Fouke Monster','The Honey Island Swamp Monster','The Beast of Bladenboro',
    'The Minerva Monster','The Van Meter Visitor','The Shunka Warakin',
    'The Enfield Horror','The Snallygaster','The Squonk','The Pope Lick Monster',
    'The Goatman of Maryland','The Sheepsquatch','The White River Monster',
    'The Tahoe Tessie','Champ of Lake Champlain','The Brosno Dragon',
    'The Mongolian Death Worm','The Bunyip','The Yowie','The Taniwha',
    'The Almas','The Orang Pendek','The Ropen','Mokele-mbembe',
    'The Lusca','The Ningen','The Batsquatch','The Owlman of Mawnan',
    'The Grassman','The Bukit Timah Monkey Man','The Beast of Gévaudan',
    'The Surrey Puma','The Beast of Busco','The Michigan Dogman',
    'The Ohio Grassman','The Maryland Goatman','The Florida Skunk Ape',
    'The Texas Bigfoot','The Pacific Northwest Sasquatch','The Ozark Howler',
    'The Wampus Cat','The Hidebehind','The Wendigo of the Great Lakes',
    'The Waheela','The Nuk-luk','The Marked Hominid','The Proto-Pygmy',
    'The Mande Barung India','The Yeren of China','The Nguoi Rung Vietnam',
    'The Batutut','The Abnauayu Caucasus','The Mecheny',
    'The Kapre Philippines','The Tikbalang Philippines','The Agogwe Africa',
    'The Tokoloshe','The Popobawa Tanzania','The Grootslang South Africa',
    'The Inkanyamba South Africa','The Ngoubou Cameroon','The Emela-ntouka',
    'The Muhuru','The Lukwata Uganda','The Kipunji Tanzania','The Bili Ape Congo',
    'The Thylacine sightings Australia','The Australian Bunyip variants',
    'The Hawkesbury River Monster','The Moehau New Zealand',
    'The Waitoreke New Zealand','The Kumi Lizard','The Mbielu-Mbielu-Mbielu',
    'The Mamlambo South Africa','The Dingonek','The Kongamato flying cryptid',
    'The Nandi Bear Kenya','The Adjule North Africa','The Mngwa Tanzania',
    'The Cactus Cat','The Jackalope','The Hodag Wisconsin',
    'The Axehandle Hound','The Fur-bearing Trout','The Sidehill Gouger',
    'The Wolpertinger Bavaria','The Peryton medieval beast',
    'The Yale medieval creature','The Bonnacon medieval beast','The Leucrota',
    'The Catoblepas','The Amphisbaena','The Basilisk medieval variants',
    'The Cockatrice','The Wyvern','The Lindworm Scandinavia',
    'The Orm Norse sea serpent','The Hafgufa Norse','The Aspidochelone',
    'The Zaratan giant turtle','The Cetus sea monster','The Carbunclo',
    'The Nessie sonar contacts history','The Patterson Gimlin film analysis',
    'The Paul Freeman Bigfoot tracks','The Skookum cast Bigfoot evidence',
    'The Bossburg cripple foot tracks','The Freeman footage 1994',
    'The Marble Mountain Bigfoot footage','The Momo Missouri Monster',
    'The Knobby North Carolina cryptid','The Santer Michigan cryptid',
    'The Yahoo California creature','The Prince William Sound sea monster',
    'The Cadborosaurus sightings Pacific','The Chessie Chesapeake Bay monster',
    'The South Bay Bessie Lake Erie','The Pressie Lake Superior monster',
    'The Great Slave Lake monster Canada','The Lake Simcoe Igopogo Canada',
    'The Mussie Muskrat Lake Canada',
  ]},
  { category: 'UFOs', topics: [
    'Roswell incident 1947','Phoenix Lights 1997','Belgian UFO wave 1989',
    'Rendlesham Forest incident 1980','Travis Walton abduction 1975',
    'Bob Lazar Area 51 testimony','The Tic Tac UFO 2004','Nimitz encounter 2004',
    'Skinwalker Ranch history','Battle of Los Angeles 1942',
    'The Kecksburg UFO 1965','Tehran UFO incident 1976',
    'Shag Harbour incident 1967','Lubbock Lights 1951',
    'The Westall UFO 1966','The Washington DC UFO flap 1952',
    'The Kenneth Arnold sighting 1947','The Lonnie Zamora incident 1964',
    'The Cash-Landrum incident 1980','The Ariel School Zimbabwe 1994',
    'The Varginha incident Brazil 1996','The Frederick Valentich disappearance',
    'The Levelland UFO case 1957','The Lakenheath UFO incident 1956',
    'The Mansfield helicopter encounter 1973','The Hudson Valley UFO wave',
    'The Gulf Breeze sightings Florida','The Gorman dogfight 1948',
    'The Thomas Mantell crash 1948','JAL Flight 1628 encounter 1986',
    'The Chilean Navy UFO video 2014','The Pentagon UAP videos 2017',
    'USS Roosevelt UFO encounters','The Malmstrom AFB UFO incident',
    'The Bentwaters UFO incident','The Coyne helicopter incident 1973',
    'The Kelly Cahill abduction Australia','The Buff Ledge abduction 1968',
    'The Pascagoula abduction 1973','Betty and Barney Hill abduction 1961',
    'The Allagash abductions 1976','The Antonio Villas Boas case 1957',
    'The McMinnville UFO photographs 1950','Area 51 declassified history',
    'The Majestic 12 documents','The Robertson Panel UFO inquiry',
    'The Falcon Lake UFO incident 1967','The Ubatuba UFO fragments',
    'The Colares UFO flap Brazil 1977','The Coyame UFO incident Mexico',
    'The Zimbabwe UFO landing 1985','The Nuremberg UFO battle 1561',
    'The Basel UFO phenomenon 1566','The Sao Paulo UFO wave 1986',
    'The O Hare Airport UFO 2006','The Stephenville Texas UFO 2008',
    'The Moscow UFO wave 1990','The Petrozavodsk phenomenon Russia',
    'The Trans-en-Provence UFO France','The Valensole landing France 1965',
    'The Imjarvi Finland encounter','The Voronezh UFO landing Russia',
    'The Dalnegorsk crash Russia','The Dogon people astronomical knowledge',
    'UFOs over nuclear facilities history','UFOs shutting down nuclear missiles',
    'The Minuteman missile UFO incidents','UFOs over Chernobyl nuclear plant',
    'Underwater UFOs USOs history','USO encounters Pacific Ocean',
    'The Puerto Rico USO reports','The Norwegian spiral anomaly 2009',
    'The Black Knight satellite mystery','The Solar Warden space fleet theory',
    'Project Blue Book declassified files','Project Sign early UFO investigation',
    'Project Grudge suppression theory','The Condon Committee report controversy',
    'The Brookings Report UFO implications','CIA involvement in UFO cover-up',
    'The Advanced Aerospace Threat program','AARO UAP investigations 2023',
    'The Wilson Davis memo UFO crash retrieval','The Steven Greer disclosure project',
    'The Tom DeLonge UFO revelations','The Elizondo Pentagon testimony',
    'The Fravor tic-tac testimony','The Grusch whistleblower testimony',
    'UFO crash retrieval programs alleged','Non-human biologics testimony Congress',
    'The UAP congressional hearings 2023','Ancient UFOs in cave paintings',
    'UFOs in Renaissance art history','Medieval UFO chronicles history',
    'Alexander the Great UFO encounters','UFOs in Japanese feudal art',
    'The Socorro New Mexico landing trace','The Delphos Kansas landing ring',
    'The Voronezh landing Russia 1989','The Livingston Scotland 1979 landing',
    'The Knowles family Australia encounter','The Mundrabilla Australia encounter',
    'The Frederick Valentich transcript recording',
    'The Chiles Whitted airliner encounter','The Eastern Airlines UFO 1948',
    'The Air France UFO triangle 1994','The Colares Brazilian UFO wave details',
    'The Hudson Valley boomerang UFO','The Gulf Breeze photographs analysis',
    'The Kaikoura New Zealand UFO film','The Valentich Melbourne radio transcript',
  ]},
  { category: 'Ancient Mysteries', topics: [
    'The Nazca Lines Peru','Stonehenge construction mystery','Lost city of Atlantis',
    'The Antikythera Mechanism','Easter Island Moai mystery','Gobekli Tepe Turkey',
    'The Voynich Manuscript','Egyptian Great Pyramid secrets',
    'The Baghdad Battery','Puma Punku Bolivia','The Sacsayhuaman walls',
    'Derinkuyu underground city Turkey','The Longyou Caves China',
    'Yonaguni Monument Japan','The Plain of Jars Laos',
    'The Baalbek megaliths Lebanon','The Carnac stones France',
    'The Newgrange passage tomb Ireland','The Avebury stone circle England',
    'Tiwanaku Bolivia mysteries','The Paracas elongated skulls',
    'Crystal skulls mystery','The Shroud of Turin',
    'The Ark of the Covenant mystery','The Holy Grail history',
    'The Spear of Destiny','The Library of Alexandria secrets',
    'The Copper Scroll treasure','The Phaistos Disc Crete',
    'The Rongorongo script Easter Island','The Indus Valley script mystery',
    'The Tartaria tablets Romania','The Ica stones Peru',
    'The Coso artifact geode','The London Hammer Texas',
    'The Dendera light bulb Egypt','The Saqqara bird Egypt',
    'Machu Picchu construction mystery','The Angkor Wat astronomical alignment',
    'The Great Sphinx hidden chambers','The Hall of Records Egypt legend',
    'The Orion correlation theory','The Giza plateau water erosion mystery',
    'The Bosnian pyramids','The underwater city of Dwarka India',
    'The Richat Structure Eye of the Sahara','The Bimini Road Bahamas',
    'The Dogu figurines Japan','The Klerksdorp spheres South Africa',
    'The Acambaro figurines Mexico','The Ubaid lizardmen figurines Iraq',
    'The ancient Sumerian king list','The Anunnaki ancient astronaut theory',
    'The Epic of Gilgamesh flood parallels','The Enuma Elish creation mystery',
    'The Sumerian cuneiform astronomy','The Babylonian astronomical tablets',
    'The Mayan Long Count calendar','The Mayan astronomical precision',
    'The Dresden Codex Venus tables','The Aztec Sun Stone calendar',
    'The Olmec colossal heads mystery','The Olmec origins controversy',
    'The Teotihuacan pyramid alignment','The Teotihuacan mica mystery',
    'The Palenque astronaut sarcophagus','The Chichen Itza Kukulkan serpent',
    'The Great Zimbabwe ruins mystery','The Egyptian hieroglyphs helicopter image',
    'The Dogon Sirius B knowledge mystery','The Sirius mystery Robert Temple',
    'The Book of Enoch fallen angels','The Dead Sea Scrolls hidden content',
    'The Nag Hammadi library Gnostic secrets','The Gospel of Judas revelation',
    'The Emerald Tablet Hermes Trismegistus','The Rosicrucian mysteries history',
    'The Knights Templar hidden knowledge','The Templar treasure Rosslyn Chapel',
    'The Cathar treasure Montsegur France','The Oak Island Templar theory',
    'The Freemasonry Egyptian origins','The Solomon Temple secrets',
    'The Shroud of Turin bloodstain analysis','The Vinland Map Norse America',
    'The Newport Tower mystery Rhode Island','The Kensington Runestone Minnesota',
    'The Tucson lead crosses','The Los Lunas Decalogue Stone',
    'The Bat Creek inscription Tennessee','The Newark Holy Stones Ohio',
    'The Paracas textiles mystery','The Nazca aqueducts puquios mystery',
    'The Inca road network construction mystery','The Aztec calendar stone meaning',
    'The Maya blue pigment mystery','The Olmec writing system debate',
    'The Zapotec astronomical knowledge','The Teotihuacan obsidian trade network',
    'The Mississippi mound builders mystery','The Cahokia Woodhenge mystery',
    'The Poverty Point earthworks Louisiana','The Newark Earthworks Ohio geometry',
    'The Serpent Mound Ohio astronomical alignment','The Effigy Mounds Wisconsin',
    'The Underwater ruins of Yonaguni debate','The Eye of the Sahara Atlantis theory',
    'The Obelisks of ancient Egypt transport mystery',
    'The Abydos helicopter glyph controversy','The Great Pyramid internal chambers',
    'The Sphinx water erosion Schoch theory','The Second Sphinx theory',
    'The Hall of Records Cayce prophecy','The Egypt-Sumer connection theory',
    'The Phoenician America voyages theory','The Roman coins in America mystery',
    'The Roman empire China contact mystery','The Silk Road secret history',
    'The Antikythera ship cargo mystery','The ancient Greek computers theory',
  ]},
  { category: 'Paranormal', topics: [
    'The Amityville Horror house history','Shadow people phenomenon science',
    'The Hat Man phenomenon worldwide','The Dyatlov Pass incident full story',
    'The Bridgewater Triangle Massachusetts','The Sallie House haunting Kansas',
    'Poltergeist phenomena scientific study','Near death experiences research',
    'Electronic Voice Phenomena EVP history','The Bell Witch haunting Tennessee',
    'The Enfield Poltergeist London 1977','The Haunting of Borley Rectory',
    'The Myrtles Plantation Louisiana','The Black Monk of Pontefract England',
    'The Stone Tape theory residual haunting','The Winchester Mystery House',
    'The Tower of London ghosts history','The RMS Queen Mary haunting',
    'Eastern State Penitentiary ghosts','The Stanley Hotel haunting Colorado',
    'Waverly Hills Sanatorium Louisville','The Ancient Ram Inn England',
    'Leap Castle Ireland elemental','The Raynham Hall Brown Lady photograph',
    'The Greenbrier Ghost story Virginia','The Mackenzie Poltergeist Edinburgh',
    'The Rosenheim Poltergeist Germany 1967','Spontaneous human combustion cases',
    'Ball lightning phenomenon science','Time slips temporal anomalies cases',
    'Crisis apparitions documented cases','Deathbed visions scientific research',
    'After death communications study','Reincarnation James Leininger case',
    'The Pollock twins reincarnation England','Past life memories in children study',
    'Remote viewing CIA Stargate experiments','The Stargate Project declassified',
    'Project MKUltra mind control history','The Montauk Project claims',
    'Sleep paralysis old hag phenomenon','Demonic possession medical analysis',
    'The Exorcism of Anneliese Michel','The Roland Doe exorcism inspiration',
    'The Smurl haunting Pennsylvania','The Thornton Heath poltergeist England',
    'The Dodleston messages time computer','The Philip experiment Toronto 1972',
    'The Scole experiment England 1990s','Instrumental transcommunication ITC',
    'The Society for Psychical Research history','The Rhine ESP experiments Duke',
    'The Ganzfeld telepathy experiments results','The Princeton PEAR lab results',
    'The Global Consciousness Project data','The Pam Reynolds NDE case',
    'Children birthmarks past life wound correlation',
    'The James Huston Leininger reincarnation','Ian Stevenson reincarnation research',
    'Xenoglossy cases speaking unknown languages','The Bridey Murphy regression case',
    'Spirit photography Victorian history','The Cottingley Fairies photographs',
    'The William Hope spirit photos fraud','Kirlian photography aura research',
    'Infrasound ghost feelings Vic Tandy research',
    'The Resurrection Mary Chicago ghost','Ghosts of Gettysburg battlefield',
    'The Tower of London Anne Boleyn ghost','Glamis Castle monster chamber legend',
    'Chillingham Castle North Percy ghost','Highgate Cemetery vampire scare 1970',
    'The Lizzie Borden house haunting','The Whaley House San Diego haunting',
    'The LaLaurie Mansion New Orleans','The Annabelle doll haunting Connecticut',
    'The Perron family Conjuring haunting','The Ed and Lorraine Warren cases',
    'Robert the Doll Key West haunting','The Crying Boy painting curse England',
    'The James Dean Porsche 550 curse','The Tutankhamun curse archaeological',
    'The Hope Diamond curse Smithsonian','The Koh-i-Noor diamond curse history',
    'Demonic possession Loudun France 1634','The Salem witch trials 1692 paranormal',
    'The Pendle witches Lancashire 1612','The Matthew Hopkins witch finder England',
    'Stigmata documented Catholic cases','The Therese Neumann stigmata Germany',
    'The Padre Pio stigmata investigations','Incorruptible saints Catholic mysteries',
    'The body of Saint Bernadette Lourdes','Weeping statues Catholic phenomena',
    'The Zeitoun apparition Egypt 1968','The Fatima apparition 1917 third secret',
    'The Medjugorje apparition ongoing','The Lourdes apparitions Bernadette',
    'The Guadalupe tilma image mystery','The Knock apparition Ireland 1879',
    'The Tina Resch poltergeist Columbus Ohio','The Annabelle Raggedy Ann doll origin',
    'The Dibbuk box wine cabinet cursed','The Hands Resist Him eBay painting',
    'The Dyatlov Pass infrasound theory','The Enfield poltergeist Janet Hodgson',
    'The Black Shuck East Anglia legend','The Galleywood ghost England',
    'The Borley Rectory Harry Price investigation',
  ]},
  { category: 'Mythic Creatures', topics: [
    'Dragon mythology world origins','The Kraken Norse mythology',
    'Werewolf legends European history','Vampire folklore Slavic origins',
    'Kelpie Scottish water horse legend','The Irish Banshee folklore',
    'Wendigo Algonquian legend Canada','Medusa Greek mythology origins',
    'The Minotaur of Crete myth','Basilisk medieval bestiary legends',
    'The Djinn Islamic mythology origins','Kitsune Japanese fox spirits',
    'The Scottish Selkie legend','Baba Yaga Slavic witch mythology',
    'The Romanian Strigoi vampire','The Succubus medieval demonology',
    'The Changeling Irish fairy folklore','The Wild Hunt European legend',
    'The Green Man fertility mythology','The Black Shuck Norfolk ghost dog',
    'The Nuckelavee Orkney skinless demon','The Redcap Scottish goblin killer',
    'The Dullahan Irish headless rider','The Leanan Sidhe fairy muse Ireland',
    'The Irish Pooka shapeshifter','The Manticore Persian mythology beast',
    'The Chimera Greek fire-breathing','The Greek Sphinx riddle mythology',
    'The Lernaean Hydra Heracles myth','Cerberus Greek underworld guardian',
    'The Phoenix rebirth symbolism mythology','The Roc giant bird Arabian Nights',
    'The Persian Simurgh divine bird','The Japanese Tengu mountain warrior',
    'Oni demon Japanese folklore origins','The Kappa Japanese river trickster',
    'The Jorōgumo spider woman Japan','The Aswang Philippine shapeshifter',
    'The Manananggal Filipino viscera sucker','The Encantado Brazilian water spirit',
    'The Brazilian Mapinguari giant sloth','The Adaro Solomon Islands merman',
    'The Curupira Brazilian forest spirit','The Saci-Pererê trickster Brazil',
    'The Iara Brazilian freshwater mermaid','The Boto pink dolphin legend',
    'The Chupacabra Puerto Rico origins','The Llorona weeping woman legend',
    'The Nagual Mesoamerican shapeshifter','The Cipactli Aztec sea monster',
    'The Quetzalcoatl feathered serpent','The Chinese Dragon Long mythology',
    'The Chinese Qilin auspicious unicorn','The Chinese Pixiu wealth guardian',
    'The Fenghuang Chinese phoenix bird','The Baku Japanese nightmare devourer',
    'The Yamata no Orochi eight-headed dragon','The Yuki-onna snow woman Japan',
    'The Gashadokuro giant skeleton Japan','The Tanuki shapeshifting raccoon dog',
    'The Zashiki-warashi child house spirit','The Kodama sacred tree spirit Japan',
    'The Yurei vengeful ghost Japan','The Rusalka Slavic drowned maiden',
    'The Vodyanoy Slavic river demon','The Leshy Slavic forest master',
    'The Domovoi Slavic household spirit','The Kikimora Slavic nightmare spirit',
    'The Mavka Ukrainian forest nymph','The Romanian Strigoi expanded lore',
    'The Varcolac wolf demon Romania','The Moroi Romanian living vampire',
    'The Pricolici Romanian werewolf spirit','The Alp German incubus nightmare',
    'The Nachzehrer German corpse chewer','The Draugr Norse animated corpse',
    'The Haugbui Norse burial mound ghost','The Nøkk Scandinavian shapeshifter',
    'The Huldra Norse seductive forest woman','The Fossegrim Norwegian fiddler spirit',
    'Norse Trolls mountain mythology','The Jötunn Norse chaos giants',
    'The Valkyries Norse battle choosers','The Norns Norse fate spinners',
    'The Fenrir wolf Ragnarok prophecy','The Jormungandr Midgard serpent',
    'The Nidhogg corpse gnawing dragon','The Lamassu Assyrian gateway guardian',
    'The Anzû thunderbird Mesopotamia','The Humbaba cedar forest demon',
    'The Pazuzu Mesopotamian wind demon','The Tiamat primordial chaos dragon',
    'The Mushussu Babylonian dragon','The Griffin royal heraldic beast',
    'The Pegasus divine winged horse','The European Unicorn medieval legend',
    'The Merrow Irish ocean mermaid','The Melusine French fairy legend',
    'The Undine Paracelsus water elemental','The Nixie Germanic water seducer',
    'The Lorelei Rhine River temptress','The Greek Siren sailor destroyer',
    'The Harpy Greek wind spirit','The Lamia Greek child devourer',
    'The Empusa Greek road shapeshifter','The Tarasque Provençal monster',
    'The Peluda hairy French river beast','The Guivra French marsh dragon',
    'The White Lady German ghost roads','The Erlking Goethe forest spirit',
    'The Rübezahl capricious mountain spirit','The Nachtkrapp child stealing raven',
    'The Krampus Alpine Christmas demon','The Perchta Alpine midwinter goddess',
    'The Zmeu Romanian fire-breathing dragon','The Iele Romanian dancing fairy curse',
    'The Zmaj South Slavic beneficial dragon','The Ala Balkan storm hag demon',
    'The Tengu Karasu crow variant Japan','The Raiju lightning beast Japan',
    'The Nurikabe invisible wall monster Japan',
  ]},
  { category: 'Unexplained', topics: [
    'The Bermuda Triangle mystery origins','The Philadelphia Experiment 1943 story',
    'The Taos Hum New Mexico mystery','The Wow signal 1977 analysis',
    'Oak Island money pit treasure hunt','The Tunguska event 1908 explosion',
    'The Mary Celeste ghost ship 1872','Green Children of Woolpit England',
    'The Hessdalen Lights Norway phenomenon','The Marfa Lights Texas mystery',
    'The Georgia Guidestones mystery origin','The Oakville Blobs Washington 1994',
    'The Dybbuk Box cursed wine cabinet','The Max Headroom signal hijacking 1987',
    'The Zodiac Killer ciphers mystery','The Beale Ciphers buried treasure',
    'The Dorabella Cipher Elgar mystery','The Kryptos sculpture CIA unsolved',
    'The Tamam Shud case Australia 1948','The Somerton Man identity mystery',
    'Shortwave numbers stations mystery','The UVB-76 Russian buzzer station',
    'The Cicada 3301 internet puzzle origin','The Toynbee tiles pavement mystery',
    'The Lead Masks case Brazil 1966','The Isdal Woman Norway 1970',
    'The Black Dahlia murder mystery 1947','The Villisca Axe Murder House Iowa',
    'The Flannan Isles Lighthouse mystery 1900','The Carroll A Deering ghost ship',
    'The SS Ourang Medan ghost ship legend','The Joyita mystery Pacific 1955',
    'The Baychimo ghost ship Arctic history','The Flying Dutchman legend origins',
    'Ball lightning documented scientific cases','The Hutchison Effect claims',
    'Zero point energy suppression claims','The Rendlesham Forest binary message',
    'The Coral Castle mystery construction','The Overtoun Bridge dog suicides',
    'The Hinterkaifeck murders Germany 1922','The Phil Schneider DUMB claims',
    'The Agharti inner earth legend origins','The Symmes Hole hollow earth theory',
    'The Admiral Byrd hollow earth diary claim','Operation Highjump Antarctica mystery',
    'The Vela Incident 1979 nuclear explosion','The Oak Island flooding trap mechanism',
    'The Shakespearean authorship controversy','The Bacon cipher Shakespeare theory',
    'The Voynich zodiac section analysis','The Beale paper one text decoded',
    'The Kryptos K4 final section mystery','The D B Cooper hijacking 1971 mystery',
    'The Zodiac cipher Z340 solved 2020','The Jack the Ripper DNA evidence 2019',
    'The JFK assassination grassy knoll','The CIA JFK files 2023 declassification',
    'The RFK assassination Sirhan hypnosis theory','The MLK assassination conspiracy',
    'The Marilyn Monroe death circumstances','The Epstein prison death conspiracy',
    'The Gladio NATO stay-behind networks','The Strategy of Tension Italy history',
    'The Aldo Moro kidnapping mystery 1978','The Bologna train bombing 1980',
    'The Bavarian Illuminati origins history','The Bilderberg Group secret meetings',
    'The Skull and Bones Yale secret society','The Bohemian Grove Cremation of Care',
    'The Denver Airport murals meaning','The Georgia Guidestones R C Christian',
    'HAARP weather modification conspiracy','Chemtrails aerosol spraying conspiracy',
    'The Tesla free energy suppression history','The Rife machine cancer cure claim',
    'The flat earth modern movement psychology','The simulation theory Nick Bostrom',
    'The Mandela Effect false memory science','The Berenstain Bears collective memory',
    'The Monopoly man monocle Mandela Effect','False memory syndrome Elizabeth Loftus',
    'Urban legends origin psychology','Bloody Mary mirror ritual origins',
    'The Ouija board ideomotor effect science','The Cicada puzzle solutions history',
    'The SCP Foundation fiction origin','The Backrooms internet urban legend',
    'The Slender Man creation Something Awful','The creepypasta horror genre rise',
    'The NoSleep subreddit paranormal fiction','The Dyatlov Pass tent slash analysis',
    'The Dyatlov Pass radiation clothing mystery','The Brown Mountain lights Carolina',
    'The Min Min lights outback Australia','The Spook lights Joplin Missouri',
    'The Paulding Light Michigan mystery','The Fresno Nightcrawlers video analysis',
    'The Max Spears death conspiracy 2016','Time dilation anomaly reports',
    'The Coral Castle Leedskalnin method','The Hutchison Effect replication failures',
    'The Biefeld-Brown electrokinesis effect','UFO propulsion anti-gravity theories',
    'The Wilson Davis UFO memo analysis','The Grusch claims investigation',
    'The UAP Disclosure Act implications','Recovered UAP materials claims',
    'The Rendlesham binary code translation','The Wow signal 2016 claimed response',
    'The Voynich manuscript 2019 decryption claim','The DB Cooper parachute location',
    'The Zodiac killer 2021 identity claim','The Jack the Ripper Maybrick diary',
    'The Lost Colony Roanoke mystery','The Croatoan carving mystery',
    'The Roanoke disappearance theories','The Oak Island 90 foot stone inscription',
    'The Money Pit booby trap engineering','The Templar cipher on Oak Island',
    'The Dyatlov avalanche theory 2021','The Dyatlov secret weapon theory',
  ]},
];
